### PR TITLE
1.17.1

### PR DESCRIPTION
**Pull request by MedicOP**

### CODE REVIEW

**Comment by spannerman79** [comment]
Have you verified that Forge 1.7.10 has no issues?  Otherwise there will be a repeat of https://github.com/HexagonMC/BungeeCord/issues/152 (plus others that I'm not going to go digging for)

**Comment by MedicOP** [comment]
i did not

**Comment by spannerman79** [comment]
Until then - this PR should be a draft.

**Comment by MedicOP** [comment]
I just merged changes from upstream, don't see why it would break anything

**Comment by spannerman79** [comment]
Well it is obvious that you didn't even bother to read/check the linked issue for you to make that comment.

**Comment by MedicOP** [comment]
I did and I don't see how this commit would break anything. Since you seem to know so much about this issue from 3 years ago, why don't you go check it yourself then?

**Comment by spannerman79** [comment]
Well you see, if in fact it was **my** PR I would have **before** pushing it from a draft to a full PR.

Stop deflecting.

**Comment by MedicOP** [comment]
It's up to the repository owner whether he wants to merge this PR or not.

The issue is irrelevant to me and I'm not going to bother setting up a whole Forge 1.7.10 server and client just to test it.

If the developer doesn't want this PR then he can simply close it, so simple.

I'm using this on my own production server with 100+ players with no issues.

Didn't expect so much shit for contributing a PR out of the kindness of my own heart, could have easily kept this to myself while others wait for the actual developer to update to 1.17.1.

Dickhead

**Comment by spannerman79** [comment]
> The issue is irrelevant to me and I'm not going to bother setting up a whole Forge 1.7.10 server and client just to test it.

https://github.com/HexagonMC/BungeeCord/blob/master/README.md#L9


> Didn't expect so much shit for contributing a PR out of the kindness of my own heart, could have easily kept this to myself while others wait for the actual developer to update to 1.17.1.

A contribution assumes that you have done due dillagace and tested any changes which may confict with the repo's purpose.  For which I have already shown a single line from `README.md`.


> Dickhead

Shows how little you do your own checking on what this particular fork is ment for.

**Comment by johnfriedrich** [comment]
Hello, thanks for your work, however I prefer to do the merge myself. In case of issues it's easier for me to locate where they could be or what have caused them

**Comment by MedicOP** [comment]
@spannerman79 Actual developer's PR and mine ended up being exactly the same. Thanks for arguing over nothing

**Pull request closed without merging**
